### ISSUE TITLE
Um how exactly does one get this project up and running

### ISSUE THREAD

**Issue by petercr** [michaelpumo/michaelpumo#3]
Hello 👋  How's it going? 
I'm the same guy from Reddit and Twitter `@petecapecod`  who said he would check out your project regarding the Lighthouse Audit score.  You site looks awesome 🎆 

So I went ahead and forked this repo, cloned it, and ran `npm install`
Then I ran `npm run develop` after globally installing Gridsome 😉 
Here's the error I get:
```bash
Gridsome v0.7.13

Initializing plugins...
Load sources - 0s
FetchError: invalid json response body at https://undefined.prismic.io/api reason: Unexpected token < in JSON at position 0
    at /home/peterc/michaelpumo/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GraphQLSource.getRemoteExecutableSchema (/home/peterc/michaelpumo/node_modules/gridsome-source-graphql-prismic/index.js:75:20)
    at async /home/peterc/michaelpumo/node_modules/gridsome-source-graphql-prismic/index.js:50:28
    at async Plugins.run (/home/peterc/michaelpumo/node_modules/gridsome/lib/app/Plugins.js:141:11)
    at async Plugins.createSchema (/home/peterc/michaelpumo/node_modules/gridsome/lib/app/Plugins.js:85:21)
```

Looks like it's trying to connect to Prismic on the back end I think.
 
What I'm getting at is that it doesn't work, and maybe adding some instructions as to the `README` file as to how to do that. Then if anyone else wants to get it up and running, they will know how. 

Thanks

**Comment by michaelpumo** [comment]
Hi Peter...much appreciate this!

This is happening because you need a `.env` file with all the appropriate variables. I have now commit an example `.env.example` file showing this.

For the most part, you wont need the vars other than PRISMIC_REPOSITORY (which is the Prismic CMS). The value for that should be set to **michaelpumo** (the public name of my Prismic repository).

All other vars you can probably ignore, as they're private keys etc to connect the email form etc to SendGrid and MailChimp.

So, you should copy `.env.example` to a new file called `.env` and set PRISMIC_REPOSITORY to **michaelpumo**.

**Comment by petercr** [comment]
Sweet thanks so much 👍  Yeah I probably should have just figured it out myself, but it was pretty late. Plus I figured it would be good practice to get used to writing a _**how to get up and running**_ section in your `README` file. 

That being said, I forget to do it myself **_ALL OF THE TIME_** 😆 🤣 
Thanks for getting back to me

**Comment by petercr** [comment]
I totally got this working with that info. I only had to add the first part of the URL, but it works 🥳

I'll go ahead and close the issue 👍
